# Generated by Django 3.2.12 on 2022-04-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20220408_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('grams', models.IntegerField(help_text='Kg/Ml')),
                ('registered_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.registeredfood')),
            ],
            options={
                'verbose_name': 'Food Consumed',
                'verbose_name_plural': 'Foods Consumed',
            },
        ),
    ]
